name: Repository Dispatch Event

on:
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        env:
          # Set the required variables
          repo_owner: panatchakorn
          repo_name: SeleniumJavaDemo
          event_type: test-event
          runner: ubuntu-latest
          environment: env3
          description: Repository dispatch trigger test workflow
        run: |  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_WORKFLOW_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"Runner\": \"$runner\", \"Environment\": \"$environment\", \"Description\": \"$description\"}}"
