name: Workflow Dispatch Event

on:
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        env:
          repo_owner: panatchakorn
          repo_name: SeleniumJavaDemo
          event_type: test-event
          runner: ubuntu-latest
          environment: env2
          description: Workflow dispatch trigger test workflow
        run: |
          response=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TRIGGER_WORKFLOW_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/target-workflow.yml/dispatches \
          -d "{"ref":"master","inputs":{"Runner":"'"$runner"'","Environment":"'"$environment"'","Description":"'"$description"'"}}")
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          echo "$response"

      - name: Get Triggered Workflow Run Details
        id: get_run_id
        env:
          repo_owner: panatchakorn
          repo_name: SeleniumJavaDemo
        run: |
          sleep 10
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_WORKFLOW_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/target-workflow.yml/runs?per_page=1)   
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          echo "$response"
          run_id=$(echo $response | jq '.workflow_runs[0].id')
          run_html_url=$(echo $response | jq -r '.workflow_runs[0].html_url')
          run_number=$(echo $response | jq '.workflow_runs[0].run_number')
          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          echo "run_id=$run_id" >> $GITHUB_ENV
          echo "run_html_url=$run_html_url" >> $GITHUB_ENV
          echo "run_number=$run_number" >> $GITHUB_ENV
          echo "Run ID: $run_id"
          echo "Run URL: $run_html_url"
          echo "Run Number: $run_number"